import CenteredLayout from '@/components/layouts/CenteredLayout';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'SecilStore - Login',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <CenteredLayout>{children}</CenteredLayout>;
}
