import LoginStoreProvider from '@/providers/LoginStoreProvider';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'SecilStore - Login',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LoginStoreProvider>{children}</LoginStoreProvider>;
}
